// Auto-generated Live Components Registration
// Generated by @fluxstack/live — DO NOT EDIT MANUALLY
// Generated at: 2026-04-04T21:28:07.904Z

import { LiveAdminPanel } from "./LiveAdminPanel"
import { LiveCounter } from "./LiveCounter"
import { LiveDSTP } from "./LiveDSTP"
import { LiveForm } from "./LiveForm"
import { LiveLocalCounter } from "./LiveLocalCounter"
import { LivePingPong } from "./LivePingPong"
import { LiveProtectedChat } from "./LiveProtectedChat"
import { LiveRoomChat } from "./LiveRoomChat"
import { LiveSharedCounter } from "./LiveSharedCounter"
import { LiveUpload } from "./LiveUpload"

// Component classes array for LiveServer({ components }) option
export const liveComponentClasses = [
  LiveAdminPanel,
  LiveCounter,
  LiveDSTP,
  LiveForm,
  LiveLocalCounter,
  LivePingPong,
  LiveProtectedChat,
  LiveRoomChat,
  LiveSharedCounter,
  LiveUpload,
]
