// Auto-generated Live Components Registration
// Generated by @fluxstack/live — DO NOT EDIT MANUALLY
// Generated at: 2026-04-04T21:28:07.891Z

import { LiveAdminPanel } from "@app/server/live/LiveAdminPanel"
import { LiveCounter } from "@app/server/live/LiveCounter"
import { LiveDSTP } from "@app/server/live/LiveDSTP"
import { LiveForm } from "@app/server/live/LiveForm"
import { LiveLocalCounter } from "@app/server/live/LiveLocalCounter"
import { LivePingPong } from "@app/server/live/LivePingPong"
import { LiveProtectedChat } from "@app/server/live/LiveProtectedChat"
import { LiveRoomChat } from "@app/server/live/LiveRoomChat"
import { LiveSharedCounter } from "@app/server/live/LiveSharedCounter"
import { LiveUpload } from "@app/server/live/LiveUpload"

// Component classes array for LiveServer({ components }) option
export const liveComponentClasses = [
  LiveAdminPanel,
  LiveCounter,
  LiveDSTP,
  LiveForm,
  LiveLocalCounter,
  LivePingPong,
  LiveProtectedChat,
  LiveRoomChat,
  LiveSharedCounter,
  LiveUpload,
]
